#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

#
# nethcti-server-update
#
my $event = "nethcti-server-update";
templates2events("/etc/nethcti/asterisk.json",$event);
templates2events("/etc/nethcti/services.json",$event);
templates2events("/etc/nethcti/nethcti.json",$event);
templates2events("/etc/httpd/conf.d/nethcti-server.conf",$event);
safe_symlink("reload", "root/etc/e-smith/events/$event/services2adjust/httpd");
event_link("asterisk-reload", $event, "30");
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/nethcti-server");

#
# hostname-modify
#
$event = "hostname-modify";
templates2events("/etc/nethcti/nethcti.json",$event);
templates2events("/etc/nethcti/services.json",$event);
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/nethcti-server");
