#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

#
# nethcti-server3-update
#

event_templates('nethcti-server3-update', qw(
                /etc/nethcti/asterisk.json
                /etc/nethcti/dbstatic.json
                /etc/nethcti/services.json
                /etc/nethcti/nethcti.json
                /etc/nethcti/phone_urls.json
                /etc/httpd/conf.d/nethcti-server.conf
));

event_actions('nethcti-server3-update', qw(
	            nethcti-server-conf 00
));

event_services('nethcti-server3-update', qw(
               httpd reload
               nethcti-server restart
));

#
# hostname-modify
#
event_templates('hostname-modify', qw(
                /etc/nethcti/nethcti.json
                /etc/nethcti/services.json
));

event_services('hostname-modify', qw(
               nethcti-server restart
));
