#!/bin/sh
#
# ardad - Nethesis Monitor System
#
# chkconfig:   345 99 01
# description: Nethesis monitor system.
# 

# Source function library.
. /etc/rc.d/init.d/functions

helper="/usr/lib/node/forever/bin/forever"
exec="/usr/lib/node/proxycti/proxycti.js"
prog=$(basename $exec)

LOGFILE=/var/log/forever_$prog.log
PID=/var/run/$prog.pid

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

lockfile=/var/lock/subsys/$prog

start() {
    echo -n $"Starting $prog: "
    daemon "$helper start -a -l $LOGFILE -o $LOGFILE -e $LOGFILE -p $PID $exec"
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    $helper stop  $exec
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}
case "$1" in
    start|stop|restart)
        $1
        ;;
    force-reload)
        restart
        ;;
    status)
        $helper list 
        ;;
    reload)
        # If config can be reloaded without restarting, implement it here,
        # remove the "exit", and add "reload" to the usage message below.
        # For example:
        # status $prog >/dev/null || exit 7
        # killproc $prog -HUP
        action $"Service ${0##*/} does not support the reload action: " /bin/false
        exit 3
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|force-reload}"
        exit 2
esac

