#!/bin/sh
#
# ardad - Nethesis Monitor System
#
# chkconfig:   345 99 01
# description: Nethesis monitor system.
# 

# Source function library.
. /etc/rc.d/init.d/functions

helper="/usr/lib/node/forever/bin/forever"
exec="/usr/lib/node/proxycti/proxycti.js"
prog=$(basename $exec)
dirname=$(dirname $exec)

LOGFILE=/var/log/forever_$prog.log

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

lockfile=/var/lock/subsys/$prog

start() {
    /bin/chown asterisk:asterisk $LOGFILE 2>/dev/null
    /bin/chown asterisk:asterisk /var/log/asterisk/proxycti.log 2>/dev/null
    echo -n $"Starting $prog: "
    daemon  --user asterisk "cd $dirname; $helper start -a -l $LOGFILE -o $LOGFILE -e $LOGFILE -p /var/run/asterisk $prog"
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    daemon  --user asterisk "cd $dirname; $helper stop -p /var/run/asterisk $prog"
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}
case "$1" in
    start|stop|restart)
        $1
        ;;
    status)
        cd $dirname; $helper list 
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart}"
        exit 2
esac

