#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);


service_link_enhanced('proxycti', 'S98', '7');
service_link_enhanced('proxycti', 'K02', '6');
service_link_enhanced('proxycti', 'K02', '2');
service_link_enhanced('proxycti', 'K02', '1');
service_link_enhanced('proxycti', 'K02', '0');

#
# proxycti-update
#
my $event = "proxycti-update";
templates2events("/etc/asterisk/manager.conf", $event);
templates2events("/etc/crontab",$event);
templates2events("/etc/nethcti/authentication.json",$event);
templates2events("/etc/nethcti/services.json",$event);
templates2events("/etc/nethcti/chat.json",$event);
templates2events("/etc/nethcti/dbstatic.json",$event);
templates2events("/etc/nethcti/mailer.json",$event);
event_link("proxycti-conf", $event, 20);
event_link("asterisk-reload", $event, "30");
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/proxycti");


#
# bootstrap-console-save 
#
$event = "bootstrap-console-save";
templates2events("/etc/nethcti/authentication.json",$event);
templates2events("/etc/nethcti/chat.json",$event);
templates2events("/etc/nethcti/mailer.json",$event);
templates2events("/etc/nethcti/services.json",$event);



#
# pre-backup
#
$event = "pre-backup";
event_link("proxycti-backup", $event, "89");

#
# logrotate
#
$event = 'logrotate';
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/proxycti");


