#!/bin/bash

DB=`/usr/bin/mysqlshow --defaults-file=/root/.my.cnf | /bin/grep -o nethcti2`
if [ "$DB" == "nethcti2" ]; then
    # update
    if [ -f /usr/lib/node/nethcti-server/docs/db_tables/update.sh ]; then
        ln -s /usr/lib/node/nethcti-server/docs/db_tables/update.sh /etc/e-smith/sql/init/20nethcti2_update
        /sbin/service mysql.init start
    fi
else
    # install
    ln -s /usr/lib/node/nethcti-server/docs/db_tables/nethcti2.sql /etc/e-smith/sql/init/10nethcti2.sql
    /sbin/service mysql.init start
    PASS=$(perl -e 'use NethServer::Password; my $ctidb_pwd = NethServer::Password::store("CTIDBPasswd"); print ($ctidb_pwd);')
    /usr/bin/mysql --defaults-file=/root/.my.cnf -e "GRANT ALL ON nethcti2.* TO nethcti@localhost  IDENTIFIED BY '$PASS';FLUSH PRIVILEGES;"
fi

/var/lib/asterisk/bin/retrieve_nethcti_from_mysql.pl
