#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);


service_link_enhanced('nethcti-server', 'S98', '7');
service_link_enhanced('nethcti-server', 'K02', '6');
service_link_enhanced('nethcti-server', 'K02', '2');
service_link_enhanced('nethcti-server', 'K02', '1');
service_link_enhanced('nethcti-server', 'K02', '0');

#
# nethcti-server-update
#
my $event = "nethcti-server-update";
templates2events("/etc/asterisk/manager.conf", $event);
templates2events("/etc/crontab",$event);
templates2events("/etc/nethcti/authentication.json",$event);
templates2events("/etc/nethcti/services.json",$event);
templates2events("/etc/nethcti/chat.json",$event);
templates2events("/etc/nethcti/dbstatic.json",$event);
templates2events("/etc/nethcti/mailer.json",$event);
templates2events("/etc/httpd/conf/httpd.conf",$event);
safe_symlink("sigusr1", "root/etc/e-smith/events/$event/services2adjust/httpd-e-smith");
event_link("initialize-default-databases", $event, 20);
event_link("nethcti-server-conf", $event, 20);
event_link("asterisk-reload", $event, "30");
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/nethcti-server");


#
# bootstrap-console-save 
#
$event = "bootstrap-console-save";
templates2events("/etc/nethcti/authentication.json",$event);
templates2events("/etc/nethcti/chat.json",$event);
templates2events("/etc/nethcti/mailer.json",$event);
templates2events("/etc/nethcti/services.json",$event);



#
# logrotate
#
$event = 'logrotate';
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/nethcti-server");


