#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

#
# nethcti-server-update
#
my $event = "nethcti-server-update";
templates2events("/etc/asterisk/manager.conf", $event);
templates2events("/etc/nethcti/asterisk.json",$event);
templates2events("/etc/nethcti/authentication.json",$event);
templates2events("/etc/nethcti/services.json",$event);
templates2events("/etc/nethcti/chat.json",$event);
templates2events("/etc/nethcti/dbstatic.json",$event);
templates2events("/etc/nethcti/mailer.json",$event);
templates2events("/etc/nethcti/phone_urls.json",$event);
templates2events("/etc/nethcti/win_popup.json",$event);
templates2events("/etc/nethcti/nethcti.json",$event);
templates2events("/etc/httpd/conf/httpd.conf",$event);
templates2events("/etc/nethcti/sms_config.php",$event);
templates2events("/etc/nethcti/nethcti.pem",$event);
safe_symlink("reload", "root/etc/e-smith/events/$event/services2adjust/httpd");
event_link("initialize-default-databases", $event, '02');
event_link("nethcti-server-conf", $event, 20);
event_link("asterisk-reload", $event, "30");
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/nethcti-server");

#
# certificate-update
#
$event = "certificate-update";
templates2events("/etc/nethcti/nethcti.pem",$event);

