name: Update astproxy dependency

# **What it does**: Every nigth, at midnight checks if a new version of astproxy is available.
# **Why we have it**: To avoid manually updating the npm package.
# **Who does it impact**: package.json and astproxy dependency.

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

jobs:
  update-dependency:
    name: Update astproxy dependency

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Update dependency
        working-directory: ./root/usr/lib/node/nethcti-server
        run: npm install @nethesis/astproxy@latest --save
      - name: Commit and create PR
        uses: peter-evans/create-pull-request@v3
        with:
          title: "build(deps): Update astproxy dependency (automated)"
          branch-suffix: "timestamp"
          branch: "astproxy-dependency/patch"
          commit-message: "build(deps): NPM: update astproxy dependency (automated)"
